; ZCodeClass.j

; Generated by ClassFileAnalyzer (Can)
; Analyzer and Disassembler for Java class files
; (Jasmin syntax 2, http://jasmin.sourceforge.net)
;
; ClassFileAnalyzer, version 0.7.0 


.bytecode 61.0
.source ZcodeClass.java
.class public ZCodeClass
.super java/lang/Object

.method public <init>()V
  .limit stack 1
  .limit locals 1
  .line 4
  0: aload_0
  1: invokespecial java/lang/Object/<init>()V
  4: return
.end method

.method public static main([Ljava/lang/String;)V
  .limit stack 7
  .limit locals 3
  .line 7
  0: iconst_1
  1: anewarray java/lang/String
  4: dup
  5: iconst_0
  6: ldc "1"
  8: aastore
  9: astore_1
  .line 8
  10: iconst_1
  11: anewarray [Ljava/lang/String;
  14: dup
  15: iconst_0
  16: iconst_1
  17: anewarray java/lang/String
  20: dup
  21: iconst_0
  22: ldc "1"
  24: aastore
  25: aastore
  26: astore_2
  .line 9
  27: return
.end method

